# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'podimotester'
version: '1.0.0'
config-version: 2
 
# This setting configures which "profile" dbt uses for this project.
profile: 'default'
 
# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
 
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
 
 




models:
  podimotester:
    marts:
      finance:
        expose:
          +schema: 'finance'
          +materialized: table
      commercial:
        expose:
          +schema: 'commercial'
          +materialized: table
          +persist_docs:
            relation: true
            columns: true
    staging:
      +schema: 'staging'
    

on-run-start:
  - >
    CREATE TABLE IF NOT EXISTS `{{env_var('DBT_GCPPROJECT')}}.temp.dbt_log`
    (start_time TIMESTAMP,
     invocation_id STRING,
     project_name STRING)
  - >
    INSERT INTO `{{env_var('DBT_GCPPROJECT')}}.temp.dbt_log` VALUES
    (CURRENT_TIMESTAMP(),
     '{{invocation_id}}',
     '{{project_name}}')